logging:
  level: INFO
  loggers:
    org.example: DEBUG

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    port: 4000
    type: http

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/hello_world?autoReconnect=true&useSSL=false
  user: root
  password: abcdefgh
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true
